### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by RobertRajcool** [incuna/django-wkhtmltopdf#133]
Internal Server Error: /pdf/
Traceback (most recent call last):
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/wkhtmltopdf/views.py", line 78, in rendered_content
    cmd_options=cmd_options
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/wkhtmltopdf/utils.py", line 186, in render_pdf_from_template
    cmd_options=cmd_options)
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/wkhtmltopdf/utils.py", line 124, in convert_to_pdf
    return wkhtmltopdf(pages=filename, **cmd_options)
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/wkhtmltopdf/utils.py", line 110, in wkhtmltopdf
    return check_output(ck_args, **ck_kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
[02/Mar/2017 05:30:37] "GET /pdf/ HTTP/1.1" 500 116094

**Comment by johnraz** [comment]
Hi,

Copy pasting a stack trace without even saying "Hi" will not drive you far in this community.
Also there is absolutely no context around your issue, so I'm afraid that unless you improve this issue's content we are not gonna take it further.

Feel free to re-open if you improve it anyway.
