### ISSUE TITLE
CalledProcessError return exit code -11

### ISSUE THREAD

**Issue by rutcreate** [incuna/django-wkhtmltopdf#92]
I've tested several what is the cause of problem. There are 3 factors I could think of. Architecture, Django web server, and wkhtmltopdf version.

1. Ubuntu 12.04 32 bit, FastCGI, Build from source 0.12.1 => Work!
2. Ubuntu 12.04 32 bit, uWSGI, Build from source 0.12.1 => Work!
3. Ubuntu 14.10 64 bit, FastCGI, Build from source 0.12.1 => Work!
4. Ubuntu 14.10 64 bit, uWSGI, Build from source 0.12.1 => Doesn't Work!
5. Ubuntu 14.10 64 bit, python manage.py runserver, Build from source 0.12.1 => Work!
6. Ubuntu 14.10 64 bit, FastCGI, Download from website 0.12.2 => Work!
7. Ubuntu 14.10 64 bit, uWSGI, Download from website 0.12.2 => Doesn't Work!
8. Ubuntu 14.10 64 bit, python manage.py runserver, Build from source 0.12.1 => Work!

Summary from above:
1. Use FastCGI (It is going to deprecate when Django 1.9 comes) or python manage.py runserver always WORK!
2. If architecture is 64 bit, it wont' WORK with uWSGI.

I would love to see uWSGI could work on 64 bit server.

**Comment by johnraz** [comment]
Posting a decent stack trace could help to try understand the issue here, could you provide something like that?

**Comment by johnraz** [comment]
closing as we didn't get any feedback, please reopen if needs be.

**Comment by colinkingswood** [comment]
I am getting the same error on my server. (Works fine on my development laptop). 
I have tried setting the quiet option to both true and false. 

    Traceback (most recent call last):
	  File "/srv/wsgi/matchstaff-production/shared/python-env/lib/python3.4/site-packages/django/core/handlers/exception.py", line 42, in inner
	    response = get_response(request)
	  File "/srv/wsgi/matchstaff-production/shared/python-env/lib/python3.4/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
	    response = self._get_response(request)
	  File "/srv/wsgi/matchstaff-production/shared/python-env/lib/python3.4/site-packages/django/core/handlers/base.py", line 217, in _get_response
	    response = self.process_exception_by_middleware(e, request)
	  File "/srv/wsgi/matchstaff-production/shared/python-env/lib/python3.4/site-packages/django/core/handlers/base.py", line 215, in _get_response
	    response = response.render()
	  File "/srv/wsgi/matchstaff-production/shared/python-env/lib/python3.4/site-packages/django/template/response.py", line 109, in render
	    self.content = self.rendered_content
	  File "/srv/wsgi/matchstaff-production/shared/python-env/lib/python3.4/site-packages/wkhtmltopdf/views.py", line 78, in rendered_content
	    cmd_options=cmd_options
	  File "/srv/wsgi/matchstaff-production/shared/python-env/lib/python3.4/site-packages/wkhtmltopdf/utils.py", line 186, in render_pdf_from_template
	    cmd_options=cmd_options)                                                                                                                                                                  
	  File "/srv/wsgi/matchstaff-production/shared/python-env/lib/python3.4/site-packages/wkhtmltopdf/utils.py", line 124, in convert_to_pdf                                                      
	    return wkhtmltopdf(pages=filename, **cmd_options)
	  File "/srv/wsgi/matchstaff-production/shared/python-env/lib/python3.4/site-packages/wkhtmltopdf/utils.py", line 110, in wkhtmltopdf
	    return check_output(ck_args, **ck_kwargs)                                                                                                                                                 
	  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
	    raise CalledProcessError(retcode, process.args, output=output)
	subprocess.CalledProcessError: Command '['wkhtmltopdf', '--encoding', 'utf8', '--quiet', 'False', '/tmp/wkhtmltopdfotwwyuzr.html', '-']' returned non-zero exit status 1
