### ISSUE TITLE
Tests don't run with Django 1.7 or later

### ISSUE THREAD

**Issue by timb07** [incuna/django-wkhtmltopdf#93]
App loading changes introduced with Django 1.7 prevent the tests from running when `AppRegistryNotReady` is raised.

**Comment by timb07** [comment]
Note that with the above change, tests pass for Django 1.7.8, but fail for 1.8.5:

$ python ./wkhtmltopdf/tests/run.py
Creating test database for alias 'default'...
......FF....
======================================================================
FAIL: test_pdf_template_response (wkhtmltopdf.tests.tests.TestViews)
Test PDFTemplateResponse.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/django-wkhtmltopdf/wkhtmltopdf/tests/tests.py", line 214, in test_pdf_template_response
    self.assertTrue(media_url in footer_content, True)
AssertionError: False is not true : True

======================================================================
FAIL: test_pdf_template_response_to_browser (wkhtmltopdf.tests.tests.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/django-wkhtmltopdf/wkhtmltopdf/tests/tests.py", line 224, in test_pdf_template_response_to_browser
    self.test_pdf_template_response(show_content=True)
  File "/django-wkhtmltopdf/wkhtmltopdf/tests/tests.py", line 214, in test_pdf_template_response
    self.assertTrue(media_url in footer_content, True)
AssertionError: False is not true : True

----------------------------------------------------------------------
Ran 12 tests in 8.019s

FAILED (failures=2)
Destroying test database for alias 'default'...

**Comment by timb07** [comment]
Furthermore, if `unidecode` is installed, the last seven tests all fail with this error:
    $ python ./wkhtmltopdf/tests/run.py
    Creating test database for alias 'default'...
    .....EEEEEEE
    ======================================================================
    ERROR: test_pdf_response (wkhtmltopdf.tests.tests.TestViews)
    Should generate correct HttpResponse object and content type.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/django-wkhtmltopdf/wkhtmltopdf/tests/tests.py", line 127, in test_pdf_response
        response = PDFResponse(content=content, filename="nospace.pdf")
      File "/django-wkhtmltopdf/wkhtmltopdf/views.py", line 27, in __init__
        self.set_filename(filename, show_content_in_browser)
      File "/django-wkhtmltopdf/wkhtmltopdf/views.py", line 36, in set_filename
        filename = content_disposition_filename(filename)
      File "/django-wkhtmltopdf/wkhtmltopdf/utils.py", line 119, in content_disposition_filename
        return http_quote(filename)
      File "/django-wkhtmltopdf/wkhtmltopdf/utils.py", line 135, in http_quote
        string = string.replace(b'\\', b'\\\\').replace(b'"', b'\\"')
    TypeError: Can't convert 'bytes' object to str implicitly

It's the same problem as reported in issue #71.

**Comment by johnraz** [comment]
@timb07 I believe that we can close this ?

**Comment by maxpeterson** [comment]
Fixed in #94
